server:
  port: 8004

spring:
  application:
    name: provider-payment
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/hans_spring_cloud_demo?useUnicode=true&characterEncoding=utf8&useSSL=false
  cloud:
    zookeeper:
      connect-string: localhost


mybatis:
  mapper-locations: classpath:/mapper/mapper-*.xml
  type-aliases-package: com.hans.provide.payment.entities
logging:
  level:
    com.hans.provide.payment.dao: debug
