server:
  port: 3344

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
#      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    #    修改主机名
    instance-id: config-3344
    #    显示ip地址
    prefer-ip-address: true

spring:
  application:
    name: config-center-3344
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/hanxshuai/spring-cloud-config.git
          search-paths: -spring-cloud-config
          username: hanhshuai@163.com
          password: hs8023711