server:
  port: 9527

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/
  instance:
    #    修改主机名
    instance-id: cloud-gateway-service
    #    显示ip地址
    prefer-ip-address: true

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        # This route rule used to forward request to activity server
        - id: payment-rout1
          uri: http://localhost:8001
          predicates:
            - Path=/payment/get/**

        - id: payment-rout2
          uri: http://localhost:8001
          predicates:
              - Path=/payment/lb/**